pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
- name: "DIETClassifier"
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
- name: "EndpointConfig"
